### ISSUE TITLE
Run time error

### ISSUE THREAD

**Issue by gbiagomba** [thewhiteh4t/pwnedOrNot#11]
**Describe the bug**

**To Reproduce**
I ran the command ```python3 pwnedornot.py -f emails.txt```

**Expected behavior**
I expected to see results of whether or not accounts were compromised

**Screenshots**
![image](https://user-images.githubusercontent.com/5851606/51346405-924f3c80-1a6b-11e9-8a10-4cee2c624776.png)

**Desktop (please complete the following information):**
 - OS: Kali 2019
 - Browser: N/A
 - Version: N/A

**Additional context**
None.

**Comment by thewhiteh4t** [comment]
i get this error if i use tor... @gbiagomba

**Comment by N4rr34n6** [comment]
I get the same mistake, using the command 'python3 pwnedornot.py -e xxx@xxx.xxx'. I don't use Tor. From two different locations. Tested with Kali in the WSL, and with Lubuntu 16.04.5 and Lubuntu 18.04.1. 
![2019-01-19 1](https://user-images.githubusercontent.com/17154528/51431150-35978180-1c25-11e9-8f48-15d153251e96.png)

**Comment by dade80vr** [comment]
Seems to be an invalid user-agent problem. See discussion https://github.com/wKovacs64/pwned/issues/27

**Comment by wKovacs64** [comment]
Hi there, [`pwned`](https://github.com/wKovacs64/pwned) author here.

haveibeenpwned.com tightened up their Cloudflare rules. Supposedly, setting a custom UA that doesn't look like a browser will work in non-browser environments (CLI, etc.) but some people are still reporting being blocked regardless. 🤷‍♂️

**Comment by thewhiteh4t** [comment]
@wKovacs64 thanks a lot! I will push an updated soon...

**Comment by thewhiteh4t** [comment]
@wKovacs64 found the problem, user agent has to be in a specific format i.e. 
`a-b-c`
If i send a request by using 'pwnedornot' as ua it gives me 403 but if i am sending in this format i am finally getting 200

**Comment by thewhiteh4t** [comment]
https://github.com/wKovacs64/hibp/issues/60#issuecomment-457676667
