### ISSUE TITLE
error bypassing Cloudfare

### ISSUE THREAD

**Issue by blackcaty1** [thewhiteh4t/pwnedOrNot#12]
**Describe the bug**

**To Reproduce**

python3 pwnedornot.py -e email@examle.com

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04.1 LTS Kubuntu
 - Browser chrome

![example](https://user-images.githubusercontent.com/44212480/51443926-db63f280-1cf0-11e9-9d5e-c40037317ec0.png)

**Comment by dade80vr** [comment]
Same problem here #11 and also for me

**Comment by cquilodevelop1981** [comment]
The possible reason is a change in the API of:
https://haveibeenpwned
Their show the current usera of their API in the next page:
https://haveibeenpwned.com/API/Consumers
And as I can see, exist some news in the API public here:
https://haveibeenpwned.com/API/v2
Maybe this can help to solve the problem.

Greetings.

**Comment by thewhiteh4t** [comment]
https://github.com/wKovacs64/hibp/issues/60#issuecomment-457676667
