### ISSUE TITLE
Error while running a email scan

### ISSUE THREAD

**Issue by shehreyarahmedkohati** [thewhiteh4t/pwnedOrNot#13]
OS: 
KALI linux 

Followed the documentation and installed the tool correctly. 

**Command run: python pwnedornot.py --email att******e9@hotmail.com**

**Getting the following error:**

ERROR:root:'https://haveibeenpwned.com/api/v2/breachedaccount/test@example.com' returned an error. Could not collect tokens.
Traceback (most recent call last):
  File "pwnedornot.py", line 221, in <module>
    main()
  File "pwnedornot.py", line 86, in main
    cookies, user_agent = cfscrape.get_tokens('https://haveibeenpwned.com/api/v2/breachedaccount/test@example.com', user_agent='pwnedornot')
  File "/usr/local/lib/python2.7/dist-packages/cfscrape/__init__.py", line 178, in get_tokens
    resp.raise_for_status()
  File "/usr/lib/python2.7/dist-packages/requests/models.py", line 935, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://haveibeenpwned.com/api/v2/breachedaccount/test@example.com

**Comment by thewhiteh4t** [comment]
Read this : https://github.com/wKovacs64/hibp/issues/60#issuecomment-457676667
its working for some people and not working for others, contact troy hunt.

**Comment by shehreyarahmedkohati** [comment]
I encountered this error while running it in the kali command line terminal not from browser. Is that also blocked? @thewhiteh4t

**Comment by thewhiteh4t** [comment]
no that's the problem as per the api documentation i have followed all guidelines and for me it's working on multiple distros, if it was an issue at code level then it would stop working for everyone, i guess your IP is blocked that's why i am suggesting you to contact troy hunt directly, also if i am using tor i get this error otherwise it works everytime so if you are trying tor or something similar give it a go without it.

**Comment by shehreyarahmedkohati** [comment]
Not using tor. Perhaps it's the IP blocked issue.  Can you let me know where to raise this issue with troy hunt?

**Comment by daronwolff** [comment]
I'm facing the same issue.  I think is not an APP issue.
```
>] Created by : thewhiteh4t
[>] Version    : 1.1.1

[+] Checking for updates...

[+] Script is up-to-date...

[+] Bypassing Cloudflare Restriction...

ERROR:root:'https://haveibeenpwned.com/api/v2/breachedaccount/test@example.com' returned an error. Could not collect tokens.
Traceback (most recent call last):
  File "pwnedornot.py", line 221, in <module>
    main()
  File "pwnedornot.py", line 86, in main
    cookies, user_agent = cfscrape.get_tokens('https://haveibeenpwned.com/api/v2/breachedaccount/test@example.com', user_agent='pwnedornot')
  File "/usr/local/lib/python2.7/dist-packages/cfscrape/__init__.py", line 178, in get_tokens
    resp.raise_for_status()
  File "/usr/local/lib/python2.7/dist-packages/requests/models.py", line 862, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://haveibeenpwned.com/api/v2/breachedaccount/test@example.com
```

**OS:**

```
PRETTY_NAME="Kali GNU/Linux Rolling"
NAME="Kali GNU/Linux"
ID=kali
VERSION="2019.1"
VERSION_ID="2019.1"
ID_LIKE=debian

```
I checked the URL in other devices with different IPs and I get same result.


![image](https://user-images.githubusercontent.com/2779395/53031859-45c49b80-3433-11e9-905d-5cd38fbc6d21.png)

**Comment by shehreyarahmedkohati** [comment]
Yes getting the same. I'll raise it with troy hunt soon

**Comment by thewhiteh4t** [comment]
@daronwolff you will always get 403 if you visit link on any browser, api documentation says to use a custom User Agent such as name of tool / script, i have used pwnedornot
