### ISSUE TITLE
Search By Specific Breach

### ISSUE THREAD

**Issue by averagejoe365** [thewhiteh4t/pwnedOrNot#14]
**Is your feature request related to a problem? Please describe.**
No 

**Describe the solution you'd like**
We currently use PwnedOrNot in order to automate the search for pwned emails on our domain after we receive notification from HIBP. Is it possible to only have PwnedOrNot search for the specific domain indicated in the breach notification? For example, we would only need results from the Adobe.com breach.

Reference:
`https://haveibeenpwned.com/api/v2/breach/Adobe`

By version in URL (testable by clicking here):
`GET https://haveibeenpwned.com/api/v2/breach/{name}`

By api-version header:
```
GET https://haveibeenpwned.com/api/breach/{name}
api-version: 2
```

By content negotiation:
```
GET https://haveibeenpwned.com/api/breach/{name}
Accept: application/vnd.haveibeenpwned.v2+json
```

**Describe alternatives you've considered**
Currently, we are just running a find and replace to eliminate all other breaches from the returned results. 

`python pwnedornot.py -f  [filepath] -b or --breach [breachName i.e. Adobe]`

**Additional context**
If this ties back to an authorization issue, I apologize in advance. I believed the other question posed was when an individual requested that we be able to search HIBP for all accounts that were breached under a specific domain (i.e. find all @gmail accounts that have been breached). We are only asking to narrow the search for a specific breached domain (i.e. only return results from the Equifax breach for a provided list of users using the -f operator). 

Love this tool! It makes our lives so much easier when sorting though all of these messes!

**Comment by thewhiteh4t** [comment]
@averagejoe365 sorry i have been a bit busy, what you want is possible, i am creating an argument for filtering results by `breachName`, i will update as soon as i am done, also thankyou for the kind words :)

**Comment by thewhiteh4t** [comment]
@averagejoe365 I have updated the tool, major changes : 
- Added Option to Filter by Domain Name
- Added Option to get a List of all pwned Domains
- Added Option to Check if a Domain is pwned
- Added Option to Skip Password Dumps
- Speed Boost

I have updated README with Example Commands.

If you encounter any problem please open another issue, thankyou for your suggestions, Closing.
