### ISSUE TITLE
UnicodeEncodeError: 'ascii' codec can't encode character '\xe9' in position 36: ordinal not in range(128)

### ISSUE THREAD

**Issue by ston3o** [thewhiteh4t/pwnedOrNot#18]
**Describe the bug**
An error is displayed in the latest version : `UnicodeEncodeError: 'ascii' codec can't encode character '\xe9' in position 36: ordinal not in range(128)`

**To Reproduce**
`docker run -it thewhiteh4t/pwnedornot ./pwnedornot.py -e test@yopmail.com`

**Expected behavior**
No errors.

**Desktop (please complete the following information):**
- docker version : `18.09.5-ce`
- pwnedOrNot version : `1.1.7`

**Comment by superpoussin22** [comment]
will take a look

**Comment by superpoussin22** [comment]
@ston3o should be soved by #19

**Comment by thewhiteh4t** [comment]
@superpoussin22 
i have added only 2 extra lines
`
ENV LANG C.UTF-8
ENV LC_ALL C.UTF-8
`
and kept debian, also apt-get install locale was not required

**Comment by thewhiteh4t** [comment]
also changed entry point to 
`ENTRYPOINT ["python3", "pwnedornot.py"]`
now docker-entrypoint.sh is not required

**Comment by thewhiteh4t** [comment]
pushed these changes give it a go!

**Comment by superpoussin22** [comment]
ok for me

**Comment by thewhiteh4t** [comment]
@ston3o waiting for your response...

**Comment by ston3o** [comment]
Yes this error is fixed ! Thanks ;)
