### ISSUE TITLE
Killed

### ISSUE THREAD

**Issue by JaySmith502** [thewhiteh4t/pwnedOrNot#21]
Keep getting "Killed" message when running dump search on my email address, can't find in the .py code what issue may be, is it rate limiting by haveibeenpwned.com?

**Comment by thewhiteh4t** [comment]
@JaySmith502 please share output as text or a screenshot

**Comment by JaySmith502** [comment]
![Killed](https://user-images.githubusercontent.com/8827236/56474752-1ab6f200-644c-11e9-8459-9d19fcad81d5.JPG)

**Comment by JaySmith502** [comment]
Same result each time

**Comment by thewhiteh4t** [comment]
okay this is new, can you share the email address you are checking? you can send it on discord if you want : thewhiteh4t#3723

**Comment by JaySmith502** [comment]
I think I may have figured it out while running another script, my Kali install was only 512mb of RAM so I bet it was just a matter of upping the working memory, I’ll check it again tomorrow

**Comment by JaySmith502** [comment]
That was it, sorry for the confusion!
