### ISSUE TITLE
Every Time I tried

### ISSUE THREAD

**Issue by JoyGhoshs** [thewhiteh4t/pwnedOrNot#22]
json.decoder.JSONDecodeError: Unexpected UTF-8 BOM (decode using utf-8-sig): line 1 column 1 (char 0)

**Comment by thewhiteh4t** [comment]
@JoyGhoshs operating system?

**Comment by Da8tH** [comment]
Same issue here with Debian 10...

`Traceback (most recent call last):
  File "pwnedornot.py", line 247, in <module>
    main()
  File "pwnedornot.py", line 51, in main
    check()
  File "pwnedornot.py", line 88, in check
    simple_out = json.loads(json_out)
  File "/usr/lib/python3.7/json/__init__.py", line 338, in loads
    s, 0)
json.decoder.JSONDecodeError: Unexpected UTF-8 BOM (decode using utf-8-sig): line 1 column 1 (char 0)`

**Comment by thewhiteh4t** [comment]
Why am i not getting this error...i tried on kali linux, blackarch, parrot sec os, ubuntu, even on termux

**Comment by Da8tH** [comment]
could it be missing json libraries?

**Comment by thewhiteh4t** [comment]
In that case error should have been different, because if you take a look in another open issue, another user is getting this error in parrot os, so i installed fresh parrot os and updated it completely then executed pwnedornot and i did not get any errors

**Comment by thewhiteh4t** [comment]
i was able to reproduce this issue when i used pwnedornot with tor

**Comment by thewhiteh4t** [comment]
its cloudflare ddos protection :3

**Comment by Da8tH** [comment]
I see... How can I bypass Cloudflare?

**Comment by thewhiteh4t** [comment]
@Da8tH i was using CFScrape to bypass cloudflare but it is causing more problems, many users were opening issues regarding cfscrape errors, so i contacted Troy Hunt, he told me that cfscrape is actually not required so i removed it and it solved the problem for those issues but then this new issue came, i am waiting for his reply

**Comment by JoyGhoshs** [comment]
iam Using Kali Linux 2019.1

**Comment by thewhiteh4t** [comment]
@JoyGhoshs @Da8tH are you using a proxy server / vpn / tor ? if yes then fyi cloudflare blocks all requests sent via proxy / vpn / tor and Troy Hunt is not replying regarding this issue

**Comment by thewhiteh4t** [comment]
found some other open issues on this error
https://github.com/andrew-schofield/keepass2-haveibeenpwned/issues/56#issuecomment-461763129
and it looks like they are not resolved till now

**Comment by jepunband** [comment]
still waiting .. : )

**Comment by thewhiteh4t** [comment]
@jepunband what is your discord username#id ?

**Comment by jepunband** [comment]
> @jepunband what is your discord username#id ?

Discord? like in discordapp? .. i don't use it.

**Comment by thewhiteh4t** [comment]
@jepunband then telegram? Or if possible you can join any of these two?

**Comment by jepunband** [comment]
> @jepunband then telegram? Or if possible you can join any of these two?

yes telegram

**Comment by thewhiteh4t** [comment]
https://t.me/thewhiteh4t

**Comment by jepunband** [comment]
got it.
