### ISSUE TITLE
Add license

### ISSUE THREAD

**Issue by fabaff** [thewhiteh4t/pwnedOrNot#24]
Would be nice if there is a proper license statement. Thanks.

**Comment by thewhiteh4t** [comment]
@fabaff why and which license would be appropriate?

**Comment by fabaff** [comment]
Because if there is no license the tool can be ship or included in distributions. I would suggest to go with `MIT` or `ASL 2.0`.

**Comment by thewhiteh4t** [comment]
added MIT license, thankyou!
