### ISSUE TITLE
[-] Error 403 : Request Blocked by haveibeenpwned API

### ISSUE THREAD

**Issue by hedin-hiervard** [thewhiteh4t/pwnedOrNot#28]

**Comment by thewhiteh4t** [comment]
@hedin-hiervard you must have got the response body, if you are on the latest version, Send it to the email address i have given above the response body

**Comment by hedin-hiervard** [comment]
Sorry, I don't see any emails.

**Comment by thewhiteh4t** [comment]
@hedin-hiervard looks like you are on an older version, try this
`cd pwnedOrNot`
`git pull`
now execute it, i hope it works for you otherwise now you will get the full response body and email address

**Comment by BaRRaKudaRain** [comment]
Same issue. How to fix it? Does haveibeenpwned blocked against in Russia? Does VPN help in this case?
