### ISSUE TITLE
Find dumps but don't show them

### ISSUE THREAD

**Issue by DocKali** [thewhiteh4t/pwnedOrNot#29]
Hi,

I've a problem I can't solve by myself with your tool. When I run the tool on an email adress, he found breaches and in this case he found a dump too but I can't see it. 
I took a screenshot of the problem.
Thanks for your help!
![pwnedornot](https://user-images.githubusercontent.com/32202483/58161419-80331400-7c80-11e9-95f4-31547b3d4129.png)

**Comment by thewhiteh4t** [comment]
@DocKali it's possible that you came across an Email only dump, such as : 
```
1@email.com
2@email.com
3@email.com
```
That's why it did not output anything, if it's possible can you share the email ?
You can contact me via Telegram : https://t.me/thewhiteh4t

**Comment by thewhiteh4t** [comment]
@DocKali Please update by executing `git pull` inside pwnedornot dir, it will display a message now if it's unable to access the dumps.

**Comment by robertohein** [comment]
Im still having this issue. And i know that the breach is not email only because i checked with my email.
