### ISSUE TITLE
invalidad syntax when try to run

### ISSUE THREAD

**Issue by Tyferiusk** [thewhiteh4t/pwnedOrNot#33]
![image](https://user-images.githubusercontent.com/48044705/61419366-8ed62a00-a8c3-11e9-8cdb-2d3eaef7789b.png)

**Comment by Tyferiusk** [comment]
Solved, Is not python, is python3 pwendornot -h, also when i check my email, (request blocked by haveibeenpwned API)

**Comment by thewhiteh4t** [comment]
@Tyferiusk Read this https://github.com/thewhiteh4t/pwnedOrNot/issues/20#issuecomment-493819524

i have given complete request body and email which gets printed when your request is blocked by HIBP API, send that request body below `---------------` on that given email address, this is not an issue with the tool but HIBP itself

**Comment by Tyferiusk** [comment]
thx for answer dude, ill looking for a proxy :)

**Comment by thewhiteh4t** [comment]
@Tyferiusk Great, but please don't switch proxies too fast or cloudflare will block you, closing.
