### ISSUE TITLE
troyhunt new API

### ISSUE THREAD

**Issue by mzn3r** [thewhiteh4t/pwnedOrNot#34]
can't use the tools since troyHunt Authenticated API released

> Email This Complete Response at troy@troyhunt.com
-------------------------------------------------

<!DOCTYPE html>
<html>
<head>
  <title>Request Blocked</title>
  <meta charset="UTF-8" />
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
</head>
<body>
  <h1>You have been blocked from accessing this resource on Have I Been Pwned</h1>

  <p>This may be due to violating one or more of <a href="https://haveibeenpwned.com/API/v3#AcceptableUse">the acceptable use terms of the API</a> or for not complying with <a href="https://haveibeenpwned.com/API/v3">the API specifications</a>. It may also be due to your traffic patterns being similar to other users who may have violated the acceptable use terms.</p>

  <p>
    If you're not already using <a href="https://www.troyhunt.com/authentication-and-the-have-i-been-pwned-api/">the authenticated API launched in July 2019</a>,
    start now! It resolves many of the blocking issues people previously encountered by moving to
    an auth key model with controls applied to that rather to IP addresses or ASNs.
  </p>

  <div class="cf-error-details cf-error-1020">
  <h1>Access denied</h1>
  <p>This website is using a security service to protect itself from online attacks.</p>
  <ul class="cferror_details">
    <li>Ray ID: 4fb4061f3ac2afde</li>
    <li>Timestamp: 2019-07-24 07:01:37 UTC</li>
    <li>Your IP address: 37.237.xx.xx</li>
    <li class="XXX_no_wrap_overflow_hidden">Requested URL: haveibeenpwned.com/api/v2/breachedaccount/XXXXX@gmail.com </li>
    <li>Error reference number: 1020</li>
    <li>Server ID: FL_146F18</li>
    <li>User-Agent: pwnedOrNot</li>
  </ul>
</div>

</body>
</html>

**Comment by thewhiteh4t** [comment]
@mzn3r yes I am aware of the new authenticated `API v3`, currently `pwnedOrNot` is using `API v2`, and `v2` is working and will work till `August 18` , also the reason your request got blocked is listed in this blog by `Troy Hunt` : https://www.troyhunt.com/authentication-and-the-have-i-been-pwned-api/
I will update `pwnedOrNot` to work with `API v3` before `August 18`. Closing.
