### ISSUE TITLE
New API

### ISSUE THREAD

**Issue by neez333** [thewhiteh4t/pwnedOrNot#35]
curious if there is any way if we purchased an API from HIBP to add that into the script somehow to make this usable again?

**Comment by thewhiteh4t** [comment]
@neez333 https://github.com/thewhiteh4t/pwnedOrNot/issues/34#issuecomment-514543572

**Comment by thewhiteh4t** [comment]
Updated to API v3, please test and open a new issue if you encounter any error.
https://github.com/thewhiteh4t/pwnedOrNot/commit/44db4d4f4095f5d65e105dadc08706424b7d0b50

**Comment by neez333** [comment]
still fails, even after entering in my api key from HIBP

**Comment by thewhiteh4t** [comment]
@neez333 which version of pwnedornot are you using? Latest is 1.2.8

**Comment by neez333** [comment]
1.2.8 then id assume. i just did a fresh arch/blackarch install yesterday so everything is as up to date as can be

**Comment by thewhiteh4t** [comment]
@neez333 there is no point of assumption, pwnedornot displays its version when you execute it, also yesterday few people tested it with success and what exactly is the error you are getting? Can you atleast share a screenshot or text?

**Comment by neez333** [comment]
okay nevermind it does work now. must just have failed on the first initial attempt. my b

**Comment by thewhiteh4t** [comment]
Closing.
