### ISSUE TITLE
API Key formatting

### ISSUE THREAD

**Issue by klaritykarrot** [thewhiteh4t/pwnedOrNot#37]
Forgive me if this discussed elsewhere. I'm getting an error during the execution: "{ "statusCode": 401, "message": "Access denied due to improperly formed hibp-api-key." }" I simply copied the key off the receipt page and pasted into the prompt. I've deleted key.txt a couple times to try again. No go. Thanks

**Comment by thewhiteh4t** [comment]
@klaritykarrot I have updated, please try again, it should work now...
`cd pwnedornot`
`git pull`

**Comment by jawaharas** [comment]
I am getting below error with v1.2.8

[-] An Unknown Error Occurred
{ "statusCode": 401, "message": "Access denied due to improperly formed hibp-api-key." }

**Comment by fsociety699** [comment]
An Unknown Error Occurred
{ "statusCode": 401, "message": "Access denied due to improperly formed hibp-api-key." }

**Comment by fsociety699** [comment]
> @klaritykarrot I have updated, please try again, it should work now...
> `cd pwnedornot`
> `git pull`
An Unknown Error Occurred
{ "statusCode": 401, "message": "Access denied due to improperly formed hibp-api-key." }

**Comment by thewhiteh4t** [comment]
@fsociety699 try to type in the api key

**Comment by Vedecguru** [comment]
where is the Key to enter?

**Comment by bezzoh** [comment]
I have the same issue, but it was down to a mis-type of the API Key. How can I change/update this? Rather than being prompted to re-input my key I just get told its improperly formatted. 

Thank you

**Comment by thewhiteh4t** [comment]
@bezzoh inside pwnedornot directory you will see `key.txt`, you can make changes in that file

**Comment by thewhiteh4t** [comment]
@bezzoh if you copy paste it, sometimes a new line gets added, maybe that is the issue in your case

**Comment by bezzoh** [comment]
All sorted, thanks for your help
