### ISSUE TITLE
Check() failing to display Output.

### ISSUE THREAD

**Issue by bdonalds** [thewhiteh4t/pwnedOrNot#38]
I run the script with just email address

sudo python3 pwnedornot.py -e (vaild email address)

Traceback (most recent call last):
  File "pwnedornot.py", line 312, in <module>
    main()
  File "pwnedornot.py", line 69, in main
    check()
  File "pwnedornot.py", line 110, in check
    + G + '[+]' + C + ' Spam        : ' + W + str(item['IsSpamList']))
KeyError: 'Title'

**Comment by thewhiteh4t** [comment]
@bdonalds are you getting this error every time? 
Did you try any other email address?
Test with 12345@gmail.com

**Comment by bdonalds** [comment]
It continues to fail. I am using python 3.5.3

**Comment by thewhiteh4t** [comment]
@bdonalds if you use either twitter or telegram, please contact me : 
https://twitter.com/thewhiteh4t
https://t.me/thewhiteh4t

**Comment by timothe** [comment]
I have the same issue - tried on MacOS with Python 3.7.3. Listening to any solution for this now :)

**Comment by thewhiteh4t** [comment]
@timothe can you contact me on twitter or telegram? Links are above, I would highly appreciate it.

**Comment by thewhiteh4t** [comment]
@timothe thanks a lot once again! 
@bdonalds fixed in https://github.com/thewhiteh4t/pwnedOrNot/commit/9556136d4fef5bd74e511064b2295bd05b7ef23a
Closing.
