### ISSUE TITLE
HIBP API Kesys not working

### ISSUE THREAD

**Issue by Azrb** [thewhiteh4t/pwnedOrNot#39]
Seems HIBP API Keys changed/not working.

[-] An Unknown Error Occurred
{ "statusCode": 401, "message": "Access denied due to improperly formed hibp-api-key." }

**Comment by thewhiteh4t** [comment]
@Azrb are you on the latest version?

**Comment by Azrb** [comment]
> @Azrb are you on the latest version?

@thewhiteh4t .. Yes I just git cloned and checked!

**Comment by thewhiteh4t** [comment]
@Azrb I checked the documentation again there is no change in the API, did you copy paste the key or you typed it in? try typing it in and tell me if it works

**Comment by Azrb** [comment]
Purchased API from site for a month. However the output dosent shows password dumps.

shows this msg instead and says its been pwned on certain occasions : 

Looking for Dumps... [ No Dumps Found ]

**Comment by thewhiteh4t** [comment]
@Azrb yes and that's because no public dump is available for that email address, also I NEVER guaranteed that you will get a password for every email address you test, closing.

**Comment by Azrb** [comment]
@thewhiteh4t  AGREE that no public dump is available for all emails.. but when its available the program should get it.. jut trying to figure where the issue is.

[+] Looking for Dumps... [ Dumps Found ]

[-] Dumps are not Accessible...

**Comment by thewhiteh4t** [comment]
@Azrb when dumps are found and they are not accessible that means, pastebin removed a dump but hibp api has not been updated about it and pwnedornot gets an Error 404 when it tries to access that dump...

**Comment by braa250** [comment]
I want a solution

**Comment by thewhiteh4t** [comment]
@braa250 have you purchased the key?
