### ISSUE TITLE
access denied due to improperly formed hibp-api-key

### ISSUE THREAD

**Issue by kalilinusshs** [thewhiteh4t/pwnedOrNot#42]
I tried this tool on my kali Linux application in windows, but at the last step it said that 
ACCESS DENIED DUE TO IMPROPERLY FORMEDD HIBP-API-KEY
plz help me in this issue ! what should I do now ?

**Comment by thewhiteh4t** [comment]
@kalilinusshs https://github.com/thewhiteh4t/pwnedOrNot/issues/37#issuecomment-614197014

**Comment by kalilinusshs** [comment]
> @kalilinusshs #37 (comment)

ohh ! means I will have to buy the api key ? isn't it ?!
I thought this tool is free...

**Comment by thewhiteh4t** [comment]
@kalilinusshs lol I have mentioned it in the README, it used to be free but HIBP made the API paid
