### ISSUE TITLE
Acces denied - API

### ISSUE THREAD

**Issue by WeaWiz** [thewhiteh4t/pwnedOrNot#47]
First use response:
"statusCode": 401, "message": "Access denied due to improperly formed hibp-api-key." 

Now what?

**Comment by thewhiteh4t** [comment]
@WeaWiz remove trailing white space

**Comment by WeaWiz** [comment]
> @WeaWiz remove trailing white space

Thanks for replying? I am a newby, where can i fix that?

**Comment by thewhiteh4t** [comment]
@WeaWiz when we copy paste the key sometimes a trailing white space is added by default, inside pwnedornot directory you will see a file `key.txt` , edit the file and press enter 2 3 times then backspace until you reach last character of the key, meaning there should not be any space after the last character, i hope this makes sense

**Comment by IrishAce** [comment]
The white space/blank space solution did not resolve the issue.

**Comment by thewhiteh4t** [comment]
@IrishAce just confirming, did you purchase an API key?

**Comment by IrishAce** [comment]
No, I did not purchase an API key. Where do you purchase a key??
I just opened the `key.txt` file and made sure there were no leading or trailing blanks spaces.
