### ISSUE TITLE
SyntaxError: Invalid Syntax

### ISSUE THREAD

**Issue by SanthoshG03** [thewhiteh4t/pwnedOrNot#52]
File "pwnedornot.py", line 66
printf(f'{G[>]}{C} Created by:  {W}thewhiteh4t' )
                                                                       ^
can't able to run git clone on the terminal

the closing square brackets missing in the line 26,27,28,29
R = '\033[31m' # red
G = '\033[32m' # green
C = '\033[36m' # cyan
W = '\033[0m'  # white

**Comment by thewhiteh4t** [comment]
@SanthoshG03 please share a screenshot of the error

**Comment by SanthoshG03** [comment]
As I was replying as much as fast, I saw your notification, I can't figure out how to upload an image in github,
but still managed to get it done at least.
here you go:
https://ibb.co/yPbSskr
