### ISSUE TITLE
Syntax Error on line 48

### ISSUE THREAD

**Issue by MattBudz** [thewhiteh4t/pwnedOrNot#54]
Getting the below error on Kali 2021.2

<img width="1054" alt="Screen Shot 2021-09-09 at 4 51 30 PM" src="https://user-images.githubusercontent.com/46340573/132709761-c92187dd-19d2-4328-acad-354ed32c5ee4.png">

**Comment by redyummybread** [comment]
I have the same error. I ran install.sh then executed the python file. Using KALI subsystem on Windows.

**Comment by thewhiteh4t** [comment]
@redyummybread can you try using `python3` instead of `python`

**Comment by Vasanthsandesh** [comment]
use python 3
