### ISSUE TITLE
When running a search, I always get [ No dumps found ] - Manual API call returns results

### ISSUE THREAD

**Issue by therealcybermattlee** [thewhiteh4t/pwnedOrNot#66]
I never get passwords. Running on a fully updated Ubuntu 10.04.6 LTS, and using python3.

I have run the API Get manually in Insomnia.io and receive the 200 and a pastebin stub for the username. 

Is there perhaps something failing in this portion of the code?

![image](https://user-images.githubusercontent.com/120200457/206747277-cd386b31-f731-4a7d-8944-ead7f01bbcc0.png)

**Comment by therealcybermattlee** [comment]
![image](https://user-images.githubusercontent.com/120200457/206812580-177d9d58-8cf4-41ce-a577-1391b8425dc3.png)
This seems to fix it. Made a pull request.

**Comment by thewhiteh4t** [comment]
@therealcybermattlee nice catch! thanks a lot, it has been merged.

**Comment by therealcybermattlee** [comment]
Thank you! Great stuff here for sure. Fun demonstration for how it can be done for end users too.
