### ISSUE TITLE
Domains / Sort

### ISSUE THREAD

**Issue by Pilly170** [thewhiteh4t/pwnedOrNot#8]
Hi,
As per the other closed issued, if its possible I think a switch for domains and if domain selected only output to file.  (email, breach(s)) - emails on a domain change frequently so adding all to a file is really time consuming.

Also the ability to display results in order of breach date.

**Comment by thewhiteh4t** [comment]
Read this
[https://haveibeenpwned.com/DomainSearch](url)
Domain Search needs authorisation
